name: Close stale issues and PRs
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-stale: 28
          days-before-close: 0
          exempt-issue-labels: do-not-close
          exempt-pr-labels: do-not-close
